# Generated by Django 5.2.17 on 2026-10-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_trade_models',
            field=models.CharField(blank=True, help_text='Model ids, comma separated (e.g. M9). Only models proven in backtests belong here. Empty = the EA connects and reports but opens no trades.', max_length=200, verbose_name='Models approved for auto-trading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copy_trading_enabled',
            field=models.BooleanField(default=True, help_text='Master switch. Off = no ICT Bridge EA opens trades.', verbose_name='Auto-trading on'),
        ),
    ]
