# Generated by Django 5.2.17 on 2026-10-03 01:37

import django.db.models.deletion
from django.db import migrations, models


def create_guest_plan(apps, schema_editor):
    """A hidden "Guest" plan with every terminal feature on; the admin switches features off there."""
    Plan = apps.get_model("accounts", "Plan")
    SiteSettings = apps.get_model("accounts", "SiteSettings")
    plan, _ = Plan.objects.get_or_create(slug="guest", defaults=dict(
        name="Guest", description="Features of \"Continue as guest\" in the web terminal.",
        price=0, duration_days=0, is_vip=False, can_view_signals=True, signal_delay_minutes=0,
        allowed_models="all", ict_indicators=True, max_charts=4, can_view_trades=False,
        can_auto_trade=False, max_mt_accounts=0, ai_messages_per_day=50, alerts_limit=0,
        can_use_backtest=True, show_ads=False, max_mobile=0, max_desktop=0, max_web=0,
        is_active=True, is_public=False, sort_order=999))
    site, _ = SiteSettings.objects.get_or_create(pk=1)
    if site.guest_plan_id is None:
        site.guest_plan = plan
        site.save(update_fields=["guest_plan"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_trade_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="is_guest",
            field=models.BooleanField(
                default=False,
                help_text='Created by "Continue as guest" in the web terminal (no email or password).',
                verbose_name="Guest",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="guest_login_enabled",
            field=models.BooleanField(
                default=True,
                help_text='Shows "Continue as guest" on the web terminal\'s login screen. Each browser gets its own guest account (no email or password). Off = the button disappears and guests are locked.',
                verbose_name="Login as guest",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="guest_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Guests get the features of this plan. Edit that plan (Plans > Guest) to switch features on or off. Empty = guests are locked like users without a plan.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.plan",
                verbose_name="Guest features",
            ),
        ),
        migrations.AlterField(
            model_name="loginevent",
            name="method",
            field=models.CharField(
                choices=[
                    ("password", "Email + password"),
                    ("register", "Registration"),
                    ("device", "Device limit / change"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("trial", "Free trial"),
                    ("signup", "Account creation blocked"),
                    ("guest", "Continue as guest"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(create_guest_plan, migrations.RunPython.noop),
    ]
