# Generated by Django 5.2.18 on 2026-10-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_guest_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(choices=[('general', 'General'), ('ict', 'ICT concepts & models'), ('gold', 'Gold & metals'), ('forex', 'Forex'), ('indices', 'Indices'), ('crypto', 'Crypto'), ('ea', 'EAs & copy trading')], db_index=True, default='general', max_length=10),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('timeframe', models.CharField(blank=True, max_length=8)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('neutral', 'Neutral / education')], default='neutral', max_length=8)),
                ('image', models.TextField(blank=True, help_text='Chart picture (JPEG data URL)')),
                ('thumb', models.TextField(blank=True, help_text='Small picture for the list (JPEG data URL)')),
                ('chart', models.TextField(blank=True, help_text='Chart setup (JSON) so readers can open it in their terminal')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('reports', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False, help_text='Deleted by the author or an admin, or hidden by reports')),
                ('hidden_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community idea',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='accounts.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='accounts.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idea', 'user'), name='idea_like_once')],
            },
        ),
        migrations.CreateModel(
            name='IdeaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_set', to='accounts.idea')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idea', 'reporter'), name='idea_report_once')],
            },
        ),
    ]
