# Generated by Django 5.2.18 on 2026-10-07 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_community_ideas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_alerts_enabled',
            field=models.BooleanField(default=False, help_text='Off = no WhatsApp message is sent to anyone.', verbose_name='WhatsApp signal alerts on'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='Meta for Developers → your app → WhatsApp → API setup → Phone number ID.', max_length=40, verbose_name='Phone number ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_template',
            field=models.CharField(default='ict_signal', help_text='An approved template with 8 variables, see the help text below.', max_length=60, verbose_name='Message template name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_template_lang',
            field=models.CharField(default='en', max_length=10, verbose_name='Template language'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_token',
            field=models.CharField(blank=True, help_text='A permanent System User token with whatsapp_business_messaging permission.', max_length=600, verbose_name='Access token'),
        ),
        migrations.CreateModel(
            name='AlertPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='International format, digits only (923001234567)', max_length=20)),
                ('auto_notify', models.BooleanField(default=False, help_text='Send every new matching signal to WhatsApp')),
                ('min_grade', models.CharField(choices=[('all', 'All grades'), ('A', 'A and A+'), ('A+', 'A+ only')], default='A', max_length=4)),
                ('models_csv', models.CharField(blank=True, help_text='Empty = every model of the plan', max_length=200, verbose_name='Models')),
                ('symbols_csv', models.CharField(blank=True, help_text='Empty = every symbol', max_length=200, verbose_name='Symbols')),
                ('bias_only', models.BooleanField(default=True, help_text='Only setups with the daily bias')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal alert settings',
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_key', models.CharField(max_length=120)),
                ('channel', models.CharField(default='whatsapp', max_length=12)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('text', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal alert sent',
                'verbose_name_plural': 'Signal alerts sent',
                'constraints': [models.UniqueConstraint(fields=('user', 'signal_key', 'channel'), name='alert_once')],
            },
        ),
    ]
