# Generated by Django 5.2.18 on 2026-10-07 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_max_charts_1_to_8'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_api_key',
            field=models.CharField(blank=True, max_length=300, verbose_name='AI API key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_model',
            field=models.CharField(blank=True, help_text="Empty = the provider's default (e.g. claude-haiku-4-5, gpt-4o-mini, gemini-2.0-flash).", max_length=80, verbose_name='AI model'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_provider',
            field=models.CharField(choices=[('none', 'Off (template answers only)'), ('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq')], default='none', help_text="The model that words the chart assistant's answers (it only rewrites the engine's facts).", max_length=20, verbose_name='AI provider'),
        ),
        migrations.CreateModel(
            name='AIPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Use this key for the user's assistant answers")),
                ('provider', models.CharField(choices=[('none', 'Off (template answers only)'), ('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq')], default='anthropic', max_length=20)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI key of a user',
                'verbose_name_plural': 'AI keys of users',
            },
        ),
    ]
