# Generated by Django 5.2.18 on 2026-10-07 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ai_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='for_donations',
            field=models.BooleanField(default=False, help_text='Listed in the Donate window (terminal and website) when donations are on', verbose_name='Show for donations'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='for_plans',
            field=models.BooleanField(default=True, verbose_name='Show for plan payments'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donation_amounts',
            field=models.CharField(default='5, 10, 25, 50', help_text='Comma separated, in the donation currency', max_length=80, verbose_name='Suggested amounts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donation_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donation_text',
            field=models.TextField(blank=True, default='ICT Terminal is built by a small team. If it helps your trading, you can support its development with a donation of any size. Thank you!'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donation_title',
            field=models.CharField(default='Support ICT Terminal', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donations_enabled',
            field=models.BooleanField(default=False, help_text='Shows a Donate button in the terminal and a Support section on the website.', verbose_name='Donations on'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Transaction ID')),
                ('message', models.CharField(blank=True, max_length=300)),
                ('public', models.BooleanField(default=False, help_text='The donor agreed to show their name as a supporter')),
                ('status', models.CharField(choices=[('pending', 'Waiting for check'), ('received', 'Received'), ('rejected', 'Not received')], default='pending', max_length=10)),
                ('source', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='accounts.paymentmethod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
