# Generated by Django 5.2.18 on 2026-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_donations_and_bulk_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertprefs',
            name='chart_alerts',
            field=models.BooleanField(default=True, help_text='Send my chart alerts (price, line, zone, session, ICT events) to my channels, even when the terminal is closed'),
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='email_alerts',
            field=models.BooleanField(default=False, verbose_name='Chart alerts by email'),
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Filled in when the user connects the bot', max_length=30),
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='telegram_code',
            field=models.CharField(blank=True, help_text='One-time code of the Connect Telegram link', max_length=16),
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='telegram_signals',
            field=models.BooleanField(default=True, verbose_name='Signals on Telegram too'),
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='https:// address that gets every alert as JSON (POST)', max_length=300),
        ),
        migrations.AddField(
            model_name='alertprefs',
            name='whatsapp_chart',
            field=models.BooleanField(default=True, verbose_name='Chart alerts on WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chart_alerts_enabled',
            field=models.BooleanField(default=True, help_text="The server checks every user's chart alerts even when the terminal is closed and sends them to the channels the user turned on (WhatsApp, Telegram, email, webhook).", verbose_name='Chart alerts from the server on'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Needs EMAIL_HOST in admin_panel/.env (otherwise emails are only printed).', verbose_name='Alerts by email on'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='From @BotFather (/newbot). Empty = no Telegram alerts.', max_length=100, verbose_name='Telegram bot token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_username',
            field=models.CharField(blank=True, help_text='Without @, e.g. ICTTerminalAlertsBot. Users open t.me/<this> to connect.', max_length=60, verbose_name='Telegram bot username'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_alert_template',
            field=models.CharField(default='ict_alert', help_text='An approved template with 1 variable: {{1}} the alert text (chart alerts: price, line, zone, session, ICT events).', max_length=60, verbose_name='Chart alert template name'),
        ),
        migrations.AlterField(
            model_name='alertdelivery',
            name='signal_key',
            field=models.CharField(max_length=160),
        ),
    ]
