# Generated by Django 5.2.18 on 2026-10-08 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_server_chart_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoorder',
            name='donation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_order', to='accounts.donation'),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='key',
            field=models.CharField(blank=True, help_text='Lets a donor without an account follow the order', max_length=32),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='kind',
            field=models.CharField(choices=[('plan', 'Plan'), ('donation', 'Donation')], db_index=True, default='plan', max_length=10),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.plan'),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Plan price (or the donation) in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptoorder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Empty for a donation from a visitor without an account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
