# Generated by Django 5.2.18 on 2026-10-08 06:25

from django.db import migrations, models


def copy_trial_plans(apps, schema_editor):
    """The old "Free trial plans" were given to Google / Facebook accounts: switch those on for the same plans."""
    SiteSettings = apps.get_model("accounts", "SiteSettings")
    Plan = apps.get_model("accounts", "Plan")
    for site in SiteSettings.objects.all():
        ids = list(site.signup_plans.values_list("pk", flat=True))
        if ids:
            Plan.objects.filter(pk__in=ids).update(auto_google=True, auto_facebook=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_crypto_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='auto_email',
            field=models.BooleanField(default=False, help_text='New accounts made with email + password get this plan automatically.', verbose_name='Email sign-up'),
        ),
        migrations.AddField(
            model_name='plan',
            name='auto_facebook',
            field=models.BooleanField(default=False, help_text='New accounts made with Facebook get this plan automatically.', verbose_name='Facebook sign-up'),
        ),
        migrations.AddField(
            model_name='plan',
            name='auto_google',
            field=models.BooleanField(default=False, help_text='New accounts made with Google get this plan automatically.', verbose_name='Google sign-up'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='trial_enabled',
            field=models.BooleanField(default=True, help_text='New accounts get the plans switched on for their sign-up (Plans list: Email / Google / Facebook sign-up columns), once per account and once per phone / PC. Off = no automatic plans at all.', verbose_name='Automatic plans for new accounts'),
        ),
        migrations.AlterModelOptions(
            name='trialgrant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Free trial given', 'verbose_name_plural': 'Free trials given'},
        ),
        migrations.RunPython(copy_trial_plans, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitesettings',
            name='signup_plans',
        ),
    ]
