# Generated by Django 5.2.18 on 2026-10-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plans_per_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertprefs',
            options={'verbose_name': 'Signal alert settings', 'verbose_name_plural': 'Signal alert settings'},
        ),
        migrations.AlterModelOptions(
            name='cryptowalletchange',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Crypto wallet change (audit log)', 'verbose_name_plural': 'Crypto wallet changes (audit log)'},
        ),
    ]
