from django.urls import path

from . import api, oauth

urlpatterns = [
    path("health", api.health),
    path("plans", api.plans),
    path("auth/register", api.register),
    path("auth/login", api.login),
    path("auth/guest", api.guest),
    path("auth/logout", api.logout),
    path("auth/me", api.me),
    path("auth/password/change", api.password_change),
    path("auth/password/reset", api.password_reset),
    path("auth/password/reset/confirm", api.password_reset_confirm),
    path("app-config", api.app_config),
    path("copy/settings", api.copy_settings),
    path("copy/token", api.copy_token),
    path("payments/methods", api.payment_methods),
    path("payments/submit", api.payment_submit),
    path("payments/mine", api.payments_mine),
    path("community/status", api.community_status),
    path("community/join", api.community_join),
    path("community/messages", api.community_messages),
    path("community/messages/<int:message_id>/report", api.community_report),
    path("ads", api.ads),
    path("ads/<int:ad_id>/click", api.ad_click),
    path("ads/<int:ad_id>/image", api.ad_image, name="ad-image"),
    path("payments/crypto/networks", api.crypto_networks),
    path("payments/crypto/order", api.crypto_order_create),
    path("payments/crypto/open", api.crypto_order_open),
    path("payments/crypto/order/<int:order_id>/cancel", api.crypto_order_cancel),
    path("payments/crypto/order/<int:order_id>", api.crypto_order_status),
    path("payments/crypto/order/<int:order_id>/txid", api.crypto_order_txid),
    path("oauth/<str:provider>/start", oauth.start),
    path("oauth/<str:provider>/callback", oauth.callback),
    path("oauth/finish", oauth.finish),
    path("oauth/poll", oauth.poll),
    path("internal/verify", api.internal_verify),
    path("internal/ea", api.internal_ea),
    path("internal/site", api.internal_site),
]
